{% set name = "pycodestyle" %}
{% set version = "2.11.1" %}
{% set compress_type = "tar.gz" %}
{% set sha256 = "41ba0e7afc9752dfb53ced5489e89f8186be00e599e712660695b7a75ff2663f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ sha256 }}

build:
  entry_points:
    - pycodestyle = pycodestyle:_main
  skip: True  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pycodestyle
  requires:
    - pip
  commands:
    - pip check
    - pycodestyle --help
    - pycodestyle --version

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
  summary: Python style guide checker
  doc_url: https://pycodestyle.pycqa.org
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - jjhelmus
    - sigmavirus24
    - dopplershift
    - ocefpaf
