{% set name = "pycodestyle" %}
{% set version = "2.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 318f5db083869b4c4dad922d0b11124fb27ab181b6730b93371da671e31bd50e
  - url: https://github.com/PyCQA/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: 3cb6afba1667f13b4ca7884154299108ef8e633a36526e29412a5cec7b5db4bd
    folder: gh

build:
  entry_points:
    - pycodestyle = pycodestyle:_main
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

# self.assertEqual(errcode, 1)
# AssertionError: None != 1
{% set tests_to_skip = "test_check_diff" %}

test:
  source_files:
    - gh/tests
    - gh/testing
    - gh/setup.py
    - gh/setup.cfg
  imports:
    - pycodestyle
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -k "not {{ tests_to_skip }}" -v gh/tests
    - pycodestyle --help
    - pycodestyle --version

about:
  home: https://pycodestyle.pycqa.org
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Pycodestyle is a tool to check your Python code against some of the style conventions in PEP 8.
  summary: Python style guide checker
  doc_url: https://pycodestyle.pycqa.org
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - jjhelmus
    - sigmavirus24
    - dopplershift
    - ocefpaf