travis:
  secure:
    BINSTAR_TOKEN: dsoFZ7bDaRNgt4sd+Gr/yh3r9MOlKLSfnHh5TeFAroCM/giQIi0FV+ZUmeFwPbDT7UqAL+JTJGOibDRwyjqi/Xo9KeiW0wqDRex89j/jjoR12an1POfMrM2ldHJuogm/Kl7zXr/Xzr0itlOxnevr6iHkzJfYHZ669EfOyaMgi+HXxTVWVjYsHji2lMFmYyXPCBcgdzmhpToIIfWN5G+Um5QV0CC/HdvIa/DuCONdKv2cNSsmhTiQyqAu0Xs5Xq3NwWwNdnbNcXthjkIxOf/a2GNujeO5u4xWOFskP93tatjJkiTDle6mDqDBXc2C9zJYLjeHNYeuLl7xgQxUZVuWWrvmAp6V5XjnWC/ZYwUDtMgUNyqNAo/WldwnyxCUrCBB4A12M6H8+e5ST1wUDGHcYsM5rlR6ijlN3byDAnFfHBJcYiJTJMSliuYSxFnV8JibjeXpZWJkOEY0MvcaT16hqWRz/LPqWqRcrxLM6xeGRl8vQztxNNca7YzdkkRCQG2Q0So5AQ7A8XxxH6cPfjf8ru56GNZgghZTnTIh7TCJesuDNh8PVdWWAxtQ9pfrPfTBLMXopij/IebFLUzpk6VQz9sQ1/QOKYNy3wbxsZ71iD7cery3ejTtN3ECutLZQd6hY8JbU8j0V/T5avl2vzldM9Bow3kK9uYVd7ml157VFSg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
